services:
  - type: web
    name: jorges-video-audio-downloader
    runtime: docker
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DOWNLOADS_DIR
        value: /app/storage/downloads
      - key: DATA_DIR
        value: /app/storage/data
      - key: THUMBNAILS_DIR
        value: /app/storage/thumbnails
    disk:
      name: downloader-storage
      mountPath: /app/storage
      sizeGB: 1
