import type { GroupId, Team } from "../types";

const rawTeams: Array<Omit<Team, "groupName">> = [
  { id: "mex", name: "Mexiko", group: "A", flag: "🇲🇽", fifaCode: "MEX" },
  { id: "rsa", name: "Südafrika", group: "A", flag: "🇿🇦", fifaCode: "RSA" },
  { id: "kor", name: "Südkorea", group: "A", flag: "🇰🇷", fifaCode: "KOR" },
  { id: "cze", name: "Tschechien", group: "A", flag: "🇨🇿", fifaCode: "CZE" },
  { id: "can", name: "Kanada", group: "B", flag: "🇨🇦", fifaCode: "CAN" },
  { id: "sui", name: "Schweiz", group: "B", flag: "🇨🇭", fifaCode: "SUI" },
  { id: "qat", name: "Katar", group: "B", flag: "🇶🇦", fifaCode: "QAT" },
  { id: "bih", name: "Bosnien und Herzegowina", group: "B", flag: "🇧🇦", fifaCode: "BIH" },
  { id: "bra", name: "Brasilien", group: "C", flag: "🇧🇷", fifaCode: "BRA" },
  { id: "mar", name: "Marokko", group: "C", flag: "🇲🇦", fifaCode: "MAR" },
  { id: "hai", name: "Haiti", group: "C", flag: "🇭🇹", fifaCode: "HAI" },
  { id: "sco", name: "Schottland", group: "C", flag: "🏴", fifaCode: "SCO" },
  { id: "usa", name: "USA", group: "D", flag: "🇺🇸", fifaCode: "USA" },
  { id: "par", name: "Paraguay", group: "D", flag: "🇵🇾", fifaCode: "PAR" },
  { id: "aus", name: "Australien", group: "D", flag: "🇦🇺", fifaCode: "AUS" },
  { id: "tur", name: "Türkei", group: "D", flag: "🇹🇷", fifaCode: "TUR" },
  { id: "ger", name: "Deutschland", group: "E", flag: "🇩🇪", fifaCode: "GER" },
  { id: "cuw", name: "Curaçao", group: "E", flag: "🇨🇼", fifaCode: "CUW" },
  { id: "civ", name: "Elfenbeinküste", group: "E", flag: "🇨🇮", fifaCode: "CIV" },
  { id: "ecu", name: "Ecuador", group: "E", flag: "🇪🇨", fifaCode: "ECU" },
  { id: "ned", name: "Niederlande", group: "F", flag: "🇳🇱", fifaCode: "NED" },
  { id: "jpn", name: "Japan", group: "F", flag: "🇯🇵", fifaCode: "JPN" },
  { id: "tun", name: "Tunesien", group: "F", flag: "🇹🇳", fifaCode: "TUN" },
  { id: "swe", name: "Schweden", group: "F", flag: "🇸🇪", fifaCode: "SWE" },
  { id: "bel", name: "Belgien", group: "G", flag: "🇧🇪", fifaCode: "BEL" },
  { id: "egy", name: "Ägypten", group: "G", flag: "🇪🇬", fifaCode: "EGY" },
  { id: "irn", name: "Iran", group: "G", flag: "🇮🇷", fifaCode: "IRN" },
  { id: "nzl", name: "Neuseeland", group: "G", flag: "🇳🇿", fifaCode: "NZL" },
  { id: "esp", name: "Spanien", group: "H", flag: "🇪🇸", fifaCode: "ESP" },
  { id: "cpv", name: "Kap Verde", group: "H", flag: "🇨🇻", fifaCode: "CPV" },
  { id: "ksa", name: "Saudi-Arabien", group: "H", flag: "🇸🇦", fifaCode: "KSA" },
  { id: "uru", name: "Uruguay", group: "H", flag: "🇺🇾", fifaCode: "URU" },
  { id: "fra", name: "Frankreich", group: "I", flag: "🇫🇷", fifaCode: "FRA" },
  { id: "sen", name: "Senegal", group: "I", flag: "🇸🇳", fifaCode: "SEN" },
  { id: "nor", name: "Norwegen", group: "I", flag: "🇳🇴", fifaCode: "NOR" },
  { id: "irq", name: "Irak", group: "I", flag: "🇮🇶", fifaCode: "IRQ" },
  { id: "arg", name: "Argentinien", group: "J", flag: "🇦🇷", fifaCode: "ARG" },
  { id: "alg", name: "Algerien", group: "J", flag: "🇩🇿", fifaCode: "ALG" },
  { id: "aut", name: "Österreich", group: "J", flag: "🇦🇹", fifaCode: "AUT" },
  { id: "jor", name: "Jordanien", group: "J", flag: "🇯🇴", fifaCode: "JOR" },
  { id: "por", name: "Portugal", group: "K", flag: "🇵🇹", fifaCode: "POR" },
  { id: "uzb", name: "Usbekistan", group: "K", flag: "🇺🇿", fifaCode: "UZB" },
  { id: "col", name: "Kolumbien", group: "K", flag: "🇨🇴", fifaCode: "COL" },
  { id: "cod", name: "DR Kongo", group: "K", flag: "🇨🇩", fifaCode: "COD" },
  { id: "eng", name: "England", group: "L", flag: "🏴", fifaCode: "ENG" },
  { id: "cro", name: "Kroatien", group: "L", flag: "🇭🇷", fifaCode: "CRO" },
  { id: "gha", name: "Ghana", group: "L", flag: "🇬🇭", fifaCode: "GHA" },
  { id: "pan", name: "Panama", group: "L", flag: "🇵🇦", fifaCode: "PAN" },
];

export const teams: Team[] = rawTeams.map((team) => ({
  ...team,
  groupName: `Gruppe ${team.group}`,
}));

export const groupIds = Array.from(new Set(teams.map((team) => team.group))) as GroupId[];
